# Generated by Django 5.0.1 on 2024-02-01 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_anuncios_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.CharField(max_length=15)),
                ('estado_aprobacion', models.IntegerField(choices=[(0, 'No aprobo'), (1, 'Aprobo')])),
                ('estudiantes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.estudiantes')),
            ],
        ),
    ]
