# Generated by Django 5.0.1 on 2024-02-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_task_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificaciones',
            old_name='calificacion',
            new_name='calificaciones',
        ),
    ]
