# Generated by Django 5.0.1 on 2024-02-08 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_calificaciones_calificaciones_calificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificaciones',
            old_name='calificacion',
            new_name='notas',
        ),
    ]
