# Generated by Django 5.0.1 on 2024-02-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_calificacion_calificaciones_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
